### ISSUE TITLE
Exclamation Mark

### ISSUE THREAD

**Issue by brianteeman** [VictorGrycuk/streamdeck-repository-watcher#7]
Hi

Tried everything I can think of to get this working but no matter what I try I see a red exclamation icon on the button.

I am using streamdeck xl with software version 4.9.3.1322 and firmware 1.00.007

**Comment by VictorGrycuk** [comment]
Thanks @brianteeman for reporting the issue.

Have you checked the plug-in's log in case there is information there regarding the issue? On Windows, the log should be on the root folder of the installed plugin, `%appdata%\Elgato\StreamDeck\Plugins`.

In any case, I will try to reproduce the error.

**Comment by brianteeman** [comment]
I am brand new to the streamdeck (but not to development ;) ) so I'm sorry I didnt realise there were logs.

The following appears in the log immediately after it is dragged on to a button
```

2021-03-29 22:59:09.5958|FATAL|BarRaider.SdTools.Logger|Could not create instance of RepositoryWatcher.RepositoryWatcher with context 989FB2A428091F6AB638E64FFD0B0A54 - This may be due to an Exception raised in the constructor, or the class does not inherit PluginBase with the same constructor System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ArgumentException: The URL for the repository cannot be empty.
   at RepositoryWatcher.Models.Repository..ctor(String url)
   at RepositoryWatcher.Models.Watcher..ctor(PluginSettings settings)
   at RepositoryWatcher.Models.WatcherFactory.GetWatcher(PluginSettings settings)
   at RepositoryWatcher.RepositoryWatcher..ctor(SDConnection connection, InitialPayload payload)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at BarRaider.SdTools.PluginContainer.<Connection_OnWillAppear>d__13.MoveNext()
```

**Comment by brianteeman** [comment]
I found the problem. My fault. Newbie error. I needed to press the button to get it to work.
